### ISSUE TITLE
"Event" module name appears to conflict with classes in projects using this gem.

### ISSUE THREAD

**Issue by jsgarvin** [fedux-org/event-bus#6] opened 2016-01-19 20:53 UTC
I'm in the process up updating gems in a Rails app that has an ActiveRecord model called `Event`.

This gem is a dependency of the latest cucumber, and when I update cucumber I start getting errors on `Event`.  When I inspect the `Event` namespace in Pry, I see that it has the following constants defined...

    constants: Bus  EventNameResolveError  NameResolver  NoEventError

This seems to correlate with the `Event` module in this gem, and when I roll cucumber back to the last version that doesn't include event-bus as a dependency, the errors go away.

Please consider namespacing `Event` inside something less generic to reduce such conflicts. 

Thanks.

**Comment by maxmeyer** [comment] 2016-01-19 21:21
So the Problem is, that we use `module Event` and you have `class Event`. Correct?

**Comment by jsgarvin** [comment] 2016-01-19 21:23
Exactly

**Comment by maxmeyer** [comment] 2016-01-19 21:25
@mattwynne Should we use `Cucumber` as namespace or something similar? Do you use `Cuke` as namespace anywhere, or is there something similar we can use. Any suggestion?

**Comment by mattwynne** [comment] 2016-01-20 21:40
It did occur to me that `Event` was an odd namespace to use when you extracted this gem.

I don't think it belongs in the `Cucumber` namespace no. This is a general library that has nothing to do with Cucumber, other than that's where the code originated.

@kevinrutherford has already taken `EventBus` (see https://github.com/kevinrutherford/event_bus) which would have been a natural choice. I suggest we try to come up with an imaginative name for this gem and rename it.

How about `bus_stop` as a starter suggestion? Can anyone suggest a better name?

**Comment by aslakhellesoy** [comment] 2016-01-20 23:07
Maybe this doesn't have to be a library? Maybe it's ok to keep this code duplicated between the two libraries using this code?

Sandi Metz just wrote a relevant article explaining it better than I can: http://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction

**Comment by mattwynne** [comment] 2016-01-22 00:27
I agree Aslak. @dg-ratiodata I appreciate your hard work extracting the code but right now the cost / benefit of having the code in a separate gem from Cucumber just doesn't pay off for me. It's only a few lines of code and I'd prefer us to be able to tweak them easily if we need to.

I just released v2.3.2 of Cucumber which brings the Event Bus code back in.

**Comment by dg-ratiodata** [comment] 2016-01-25 10:23
@mattwynne I think you're right. After reading the article mentioned by @aslakhellesoy a comment of mine came into my mind. In that comment I mentioned, that I added some functionality which I added to the library, `aruba` needs, but `cucumber` does not. So re-integrating the code seems the best way to go. I will do this for aruba too. This should also reduce the work load for packagers.

**Comment by dg-ratiodata** [comment] 2016-01-25 10:24
@jsgarvin Since this gem is not a dependency of `cucumber` anymore, I'm going to close this issue.

**Closed by dg-ratiodata** 2016-01-25 10:24 UTC
